config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'lists#index'

resources :lists do 
resources :tasks
end 

get 'complete', to: 'tasks#complete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
belongs_to :list

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	def task_params
	task = Task.all
	params.require(:task).permit(:name, :term)
	end 

	def index 
	@list = List.all
	@task = if params[:term]
			Task.where('name LIKE ?', "%#{params[:term]}%")
			else
			Task.all 
			end 
	end 

	def show
	@list = List.find(params[:id])
	@task = Task.new
	end 

	def new
	@list = List.new 
	end

	def create
	list_params = params[:list].permit(:list_name)
	list = List.create(list_params)
	redirect_to lists_path(id: list.id)
	end

	def edit
	@list = List.find(params[:id])
	end

	def update
	list_params = params[:list].permit(:list_name)
	list = List.find(params[:id])
	list.update(list_params)
	redirect_to lists_path(id: list.id)
	end

	def destroy
	@list = List.find(params[:id])
	@list.destroy
	redirect_to lists_path
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index 
	@task = Task.all
	end 

	def show
	@task = Task.find(params[:id])
	end 

	def new
	@task = Task.new 
	end

	def create
	list = List.find(params[:list_id])
	task_params = params.require(:task).permit(:name, :priority, :status, :due_date)
	task = list.tasks.create(task_params)
	redirect_to list_path(id: list.id)
	end

	def edit
	@task = Task.find(params[:id])
	end

	def update
	task_params = params[:task].permit(:name, :priority, :status, :due_date)
	task = Task.find(params[:id])
	task.update(task_params)
	redirect_to list_path(id: task.list.id)
	end

	def destroy
	@task = Task.find(params[:id])
	@task.destroy
	redirect_to list_path(id: @task.list.id)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet">

  </head>

  <body>
  
  <div>
    <%-flash.each do |key,value| %>
    <% key %> 
    <%= value %>
    <%end%>
  </div>
  
  <div class = "container">
    <section>
    <nav class="navbar navbar-default">
               
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                        <a class="navbar-brand" <%= link_to "Home",{ controller: "lists", action: "index"}%></a>
                    </div>

                        <form class="navbar-form navbar-left">

                            <div class = "form-group">
                            <%= form_tag(lists_path, method: :get) do %>
                            <%= text_field_tag :term %>
                            </div>
                            <%= submit_tag 'Search' %>
                            <%end%>

                        </form>
        </nav>
        </section>
     <%= yield %>   
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<%= form_for @list, url: list_path(id: @list.id), method: :put do |f| %>
 	<div class = "row">
 	<%= f.label :list_name %>
 	</div>

 	<div class = "row">
  	<%= f.text_field :list_name %>
	</div>

	<div class = "row">
  	<%= f.submit "Update" %>
	</div>

<% end %>

app/views/lists/index.html.erb
<div class="homepage">
	
	<div class = "jumbotron">
	<h1> To-Do List Application </h1>
	</div>

<table class = "table">
	<thead>
	<th> List Name </th>
	<th> Last Update </th>
	<th> Edit List </th>
	<th> Delete List </th>
	</thead>

	<tbody>
		<% @list.each do|list| %> 
			<tr>
				<td>
				<%= link_to list.list_name, list_path(list) %> 
				</td>

				<td>
				Updated at <%= list.updated_at.strftime("%d %b %Y, %T") %>
				</td>
	
				<td> 
                <%= link_to list_path(list), class: 'btn btn-primary btn-xs' do%>
                <i class = "glyphicon glyphicon-pencil"></i> 
                <%end%>
				</td>
	
				<td>
				<%= link_to list_path(list), 
				method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do%>
                <i class = "glyphicon glyphicon-remove"></i> 
                <%end%>
				</td>
			</tr>
		<% end %> 
	</tbody>
</table>

	<div>
	<%= button_to "Create New List", new_list_path, :method => "get" %>
	</div>

</div>

app/views/lists/new.html.erb
<h1>New Task List</h1>
<%= form_for @list, url: lists_path, method: :post do |f| %>
 	<div class = "row">
 	<%= f.label :task_list_name %>
 	</div>

 	<div class = "row">
  	<%= f.text_field :list_name %>
	</div>

	<div class = "row">
  	<%= f.submit "Create" %>
	</div>

<% end %>

app/views/lists/show.html.erb
<div class = "jumbotron task_list_header">
<h1><%= @list.list_name %></h1>
<%= link_to "Edit List Name", edit_list_path(list_id: @list.id) %>
</div>

<div class = "col-md-7 task_list">
	<h3>Your Tasks</h3>
		<table class = "table">
			<thead>
			<div class = "table_head">
				<th> Task name </th>
				<th> Due </th>
				<th> Status </th>
			</div>
			</thead>

			<tbody>
				<% @list.tasks.each do |task| %>
				<tr>
					<td>
					<%= link_to task.name, list_task_path(list_id: @list.id, id: task) %> 
					</td>
					<td>
					<% if task.due_date && task.due_date < DateTime.now %>
  				 	<span class="label label-danger">Overdue</span>
  				 	<%else task.due_date && task.due_date > DateTime.now %>
  				 	Due in <%=distance_of_time_in_words(DateTime.now, task.due_date)%> 
					<% end %>
					</td>
					<td>
					<%= task.status %>
					</td>

				</tr>
				<% end %>
			</tbody>
		</table>
</div>


<div class = "col-md-1">
</div>
	
	<div class = "col-md-4">
	<%= form_for @task, url: list_tasks_path(list_id: @list.id), method: :post do |f| %>
						<h3>Create new tasks</h3>
						<div class = "row">
			  			<%= f.label :name %>
			  			</div>

					  	<div class = "row">
					 	<%= f.text_field :name %>
						</div>

					 	<p>
					 	<div class = "row">
						<%= f.label :priority %>
						</div>
						<div class = "row">
						<%= f.radio_button :priority, 'Low' %> Low 
						<%= f.radio_button :priority, 'Medium' %> Medium 
						<%= f.radio_button :priority, 'High' %> High 
						</div>
						</p>

					 	<p>
					 	<div class = "row">
						<%= f.label :status %>
						</div>
						<div class = "row">
						<%= f.radio_button :status, 'In_progress' %> In Progress 
						<%= f.radio_button :status, 'Completed' %> Completed 
						</div>
						</p>

					 	<div class = "row">
						<%= f.label :due_date %>
						</div>

						<div class = "row">
					 	<%= f.text_field :due_date %>
					 	</div>

					

					 	<br>
					 	</br>

						<div class = "row">
					  	<%= f.submit "Create" %>
						</div>
	<% end %> 	


</div>

app/views/tasks/edit.html.erb
<h3>Edit Tasks</h3>
<%= form_for @task, url: list_task_path(@task.id), method: :put do |f| %>


	<div class = "row">
  	<%= f.label :name %>
  	</div>

  	<div class = "row">
 	<%= f.text_field :name %>
	</div>

	<div class = "row">
	<%= f.label :description %>
	</div>

	<div class = "row">
 	<%= f.text_field :description %>
 	</div>

	<div class = "row">
	<%= f.label :priority %>
	</div>

	<div class = "row">
 	<%= f.text_field :priority %>
 	</div>

	<div class = "row">
	<%= f.label :status %>
	</div>

	<div class = "row">
 	<%= f.text_field :status %>
 	</div>

 		<div class = "row">
	<%= f.label :due_date %>
	</div>

	<div class = "row">
 	<%= f.text_field :due_date %>
 	</div>
	<div class = "row">
  	<%= f.submit "Update Task" %>
	</div>
<% end %> 

app/views/tasks/index.html.erb
<div class="indexpage">
<div class = "row">
<h1> Hi, welcome to Jacinta's blog< /h1>

<table>
<thead>
<th> Title </th>
<th> Author </th>
<th> Created At </th>
<th> Edit Post </th>
<th> Destroy Post </th>
</thead>

<tbody>
<% @tasks.each do|task| %> 
	<tr>
	<td>
		<%= link_to task.name, list_task_path(task) %> 
	</td>
	<td>
		<%= task.priority %> 
	</td>
	<td>
		<%= task.status %> 
	</td>
		<td>
		<%= task.due_date %> 
		</td>
	 <td> 
	 <%= link_to "Edit", edit_list_task_path(task) %>
	 </td>
	 <td>
	<%= link_to 'Destroy', list_task_path(task), 
	method: :delete, data: { confirm: 'Are you sure?' } %>
	 </td>
	</tr>
<% end %> 
</tbody>
</table>
</div>

<div class = "row">
<div class = "col-xs-4 col-xs-offset-4">
<%= button_to "Create New Post", new_post_path, :method => "get" %>
</div>
</div>
</div>

app/views/tasks/new.html.erb
NEW PAGE VIEW

app/views/tasks/show.html.erb
	<h2> <%=@task.name %> </h2>
		<table class = "table">
			<thead>
				<th> Task name </th>
				<th> Priority </th>
				<th> Status </th>
				<th> Due Date </th>
				<th> Updated </th>
				<th> Edit </th>
				<th> Delete </th>
			</thead>

			<tbody>
				<tr>
					<td>
					<%= @task.name %> 
					</td>
					<td>
					<%= @task.priority %>
					</td>
					<td>
					<%= @task.status %>
					</td>
					<td>
					<%= @task.due_date %>
					</td>
					<td>
					Updated at <%= @task.updated_at.strftime("%d %b %Y, %T") %>
					</td>
					<td>
					<%= link_to edit_list_task_path(id: @task), class: 'btn btn-primary btn-xs' do%>
                	<i class = "glyphicon glyphicon-pencil"></i> 
                	<%end%>
					</td>

					<td>
					<%= link_to list_task_path(id: @task), 
					method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do%>
                	<i class = "glyphicon glyphicon-remove"></i> 
                	<%end%>
					</td>




					<td>
					<% if @task.due_date && @task.due_date < DateTime.now %>
  				 	<span class="label label-danger">Overdue</span>
  				 	<% else %>
  				 	<span class="label label-success">On Track</span>
  				 	<% end %>
					</td>

				</tr>

			</tbody>
		</table>